// build.ts — 生成 skills-content.ts + bun build --compile 三平台单二进制
// FR-023, ADR-0017/0020, REQ-052 Task 16
import {
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  statSync,
} from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

function generateSkillsContent(): void {
  const root = "src/skills";
  const out: Record<string, string> = {};
  for (const dir of readdirSync(root)) {
    const p = join(root, dir, "SKILL.md");
    try {
      if (!statSync(p).isFile()) continue;
    } catch {
      continue;
    }
    out[`${dir}/SKILL.md`] = readFileSync(p, "utf8");
  }
  const ts =
    `// AUTO-GENERATED by build.ts — do not edit\n` +
    `export const SKILL_FILES: Record<string, string> = ${JSON.stringify(out, null, 2)};\n`;
  writeFileSync("src/commands/skills-content.ts", ts);
  console.log(`generated skills-content.ts (${Object.keys(out).length} skills)`);
}

const targets = [
  { target: "bun-darwin-arm64", outfile: "dist/yaolai-cli-darwin-arm64" },
  { target: "bun-linux-x64", outfile: "dist/yaolai-cli-linux-x64" },
  { target: "bun-windows-x64", outfile: "dist/yaolai-cli-windows-x64.exe" },
];

function compile(): void {
  mkdirSync("dist", { recursive: true });
  for (const t of targets) {
    console.log(`building ${t.target}...`);
    const r = spawnSync(
      "bun",
      [
        "build",
        "src/cli.ts",
        "--compile",
        `--target=${t.target}`,
        `--outfile=${t.outfile}`,
      ],
      { stdio: "inherit" },
    );
    if (r.status !== 0) {
      console.error(`build failed for ${t.target}`);
      process.exit(1);
    }
  }
}

generateSkillsContent();
compile();
console.log("built dist/yaolai-cli-{darwin-arm64,linux-x64,windows-x64.exe}");
