// scripts/gen-skills.ts — 把 src/skills/*/SKILL.md 内容嵌入 src/commands/skills-content.ts
// 单二进制分发依赖（FR-011/016/017，ADR-0018）。Local build.ts 与 CI release.yml 共用。
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join } from "node:path";

export function generateSkillsContent(): void {
  const root = "src/skills";
  const out: Record<string, string> = {};
  for (const dir of readdirSync(root)) {
    const p = join(root, dir, "SKILL.md");
    try {
      if (!statSync(p).isFile()) continue;
    } catch {
      continue;
    }
    out[`${dir}/SKILL.md`] = readFileSync(p, "utf8");
  }
  const ts =
    `// AUTO-GENERATED by scripts/gen-skills.ts — do not edit\n` +
    `export const SKILL_FILES: Record<string, string> = ${JSON.stringify(out, null, 2)};\n`;
  writeFileSync("src/commands/skills-content.ts", ts);
  console.log(`generated skills-content.ts (${Object.keys(out).length} skills)`);
}

if (import.meta.main) {
  generateSkillsContent();
}
